FROM apache/spark:3.5.0

USER root

# Install Python dependencies
RUN pip install --no-cache-dir \
    python-Levenshtein==0.25.1 \
    jellyfish==1.1.3 \
    pyarrow==17.0.0 \
    pandas==2.0.3 \
    opensearch-py==2.4.2

USER spark

WORKDIR /opt/spark/work-dir
